const fs = require('fs');

let content = fs.readFileSync('index.html', 'utf8');

// Replacements for brand
content = content.replace(/\bNODO\b/g, 'MAROZ');
content = content.replace(/\bnodo\b/g, 'maroz');
content = content.replace(/nodoestudio\.cl/g, 'marozestudio.cl');
content = content.replace(/\bnodo\.estudio\b/g, 'maroz.estudio');

// Replacements for spelling (tildes)
const spellingCorrections = {
    'Diseno': 'Diseño',
    'diseno': 'diseño',
    'Estrategico': 'Estratégico',
    'estrategico': 'estratégico',
    'Estrategia': 'Estrategia',
    'Accion': 'Acción',
    'accion': 'acción',
    'Coleccion': 'Colección',
    'coleccion': 'colección',
    'Colecciones': 'Colecciones',
    'colecciones': 'colecciones',
    'Metodo': 'Método',
    'metodo': 'método',
    'Ludico': 'Lúdico',
    'ludico': 'lúdico',
    'Basico': 'Básico',
    'basico': 'básico',
    'Diagnostico': 'Diagnóstico',
    'diagnostico': 'diagnóstico',
    'Tambien': 'También',
    'tambien': 'también',
    'Aqui': 'Aquí',
    'aqui': 'aquí',
    'Podras': 'Podrás',
    'podras': 'podrás',
    'Unico': 'Único',
    'unico': 'único',
    'Unica': 'Única',
    'unica': 'única',
    'Mas ': 'Más ',
    ' mas ': ' más ',
    'Japones': 'Japonés',
    'japones': 'japonés',
    'Clasica': 'Clásica',
    'clasica': 'clásica',
    'Panaderia': 'Panadería',
    'panaderia': 'panadería',
    'Optimizacion': 'Optimización',
    'optimizacion': 'optimización',
    'Estandares': 'Estándares',
    'estandares': 'estándares',
    'Exito': 'Éxito',
    'exito': 'éxito',
    'Atencion': 'Atención',
    'atencion': 'atención',
    'Solucion': 'Solución',
    'solucion': 'solución',
    'Inversion': 'Inversión',
    'inversion': 'inversión',
    'Vision': 'Visión',
    'vision': 'visión',
    'Estetica': 'Estética',
    'estetica': 'estética',
    'Funcional': 'Funcional',
    'funcional': 'funcional',
    'Espacio': 'Espacio',
    'espacio': 'espacio',
    'Mobiliario': 'Mobiliario',
    'mobiliario': 'mobiliario',
    'Fotografia': 'Fotografía',
    'fotografia': 'fotografía',
    'Guias': 'Guías',
    'guias': 'guías',
    'Construccion': 'Construcción',
    'construccion': 'construcción',
    'Rapido': 'Rápido',
    'rapido': 'rápido',
    'Facil': 'Fácil',
    'facil': 'fácil',
    'Proximo': 'Próximo',
    'proximo': 'próximo',
    'Paso': 'Paso',
    'Cafe ': 'Café ',
    'cafe ': 'café ',
    'Cafes ': 'Cafés ',
    'cafes ': 'cafés ',
    'Luz': 'Luz',
    'luces': 'luces',
    'Barberia': 'Barbería',
    'barberia': 'barbería',
    'Tienda': 'Tienda',
    'tiendas': 'tiendas',
    'Local': 'Local',
    'locales': 'locales',
    'Negocio': 'Negocio',
    'negocios': 'negocios',
    'Fisico': 'Físico',
    'fisico': 'físico',
    'Fisicos': 'Físicos',
    'fisicos': 'físicos',
    'Practico': 'Práctico',
    'practico': 'práctico',
    'Tactico': 'Táctico',
    'tactico': 'táctico',
    'Tecnico': 'Técnico',
    'tecnico': 'técnico',
    'Especifico': 'Específico',
    'especifico': 'específico',
    'Especificos': 'Específicos',
    'especificos': 'específicos',
    'Basica': 'Básica',
    'basica': 'básica',
    'Basicas': 'Básicas',
    'basicas': 'básicas',
    'Practica': 'Práctica',
    'practica': 'práctica',
    'Tactica': 'Táctica',
    'tactica': 'táctica',
    'Tecnica': 'Técnica',
    'tecnica': 'técnica',
    'Especifica': 'Específica',
    'especifica': 'específica',
    'Especificas': 'Específicas',
    'especificas': 'específicas',
    'Comun': 'Común',
    'comun': 'común',
    'Desafio': 'Desafío',
    'desafio': 'desafío',
    'Desafios': 'Desafíos',
    'desafios': 'desafíos',
    'Garantia': 'Garantía',
    'garantia': 'garantía',
    'Categoria': 'Categoría',
    'categoria': 'categoría',
    'Categorias': 'Categorías',
    'categorias': 'categorías',
    'Dia': 'Día',
    'dia ': 'día ',
    'Dias': 'Días',
    'dias': 'días',
    'Dinamico': 'Dinámico',
    'dinamico': 'dinámico',
    'Armonico': 'Armónico',
    'armonico': 'armónico',
    'Autentico': 'Auténtico',
    'autentico': 'auténtico',
    'Estandar': 'Estándar',
    'estandar': 'estándar',
    'Habitacion': 'Habitación',
    'habitacion': 'habitación',
    'Organizacion': 'Organización',
    'organizacion': 'organización',
    'Ejecucion': 'Ejecución',
    'ejecucion': 'ejecución',
    'Proyeccion': 'Proyección',
    'proyeccion': 'proyección',
    'Innovacion': 'Innovación',
    'innovacion': 'innovación',
    'Inspiracion': 'Inspiración',
    'inspiracion': 'inspiración',
    'Evaluacion': 'Evaluación',
    'evaluacion': 'evaluación',
    'Cotizacion': 'Cotización',
    'cotizacion': 'cotización'
};

for (const [wrong, right] of Object.entries(spellingCorrections)) {
    // We use a regex to match the whole word (or almost whole word)
    const regex = new RegExp('\\b' + wrong + '\\b', 'g');
    content = content.replace(regex, right);
}

// Special case for 'cafe ' -> 'café '
content = content.replace(/\bcafe\b/g, 'café');
content = content.replace(/\bCafe\b/g, 'Café');
content = content.replace(/\bmas\b/g, 'más');
content = content.replace(/\bMas\b/g, 'Más');

fs.writeFileSync('index.html', content, 'utf8');
console.log('Replaced NODO with MAROZ and fixed spelling in index.html');
