$ErrorActionPreference = 'Stop'
$content = Get-Content -Path 'index.html' -Raw -Encoding UTF8

# Replace Brand Name
$content = $content -creplace '\bNODO\b', 'MAROZ'
$content = $content -creplace '\bnodo\b', 'maroz'
$content = $content -creplace 'nodoestudio\.cl', 'marozestudio.cl'
$content = $content -creplace '\bnodo\.estudio\b', 'maroz.estudio'
$content = $content -creplace 'contacto@nodoestudio\.cl', 'contacto@marozestudio.cl'

# Replace spelling
$corrections = @(
    @('\bDiseno\b', 'Diseño'),
    @('\bdiseno\b', 'diseño'),
    @('\bEstrategico\b', 'Estratégico'),
    @('\bestrategico\b', 'estratégico'),
    @('\bAccion\b', 'Acción'),
    @('\baccion\b', 'acción'),
    @('\bColeccion\b', 'Colección'),
    @('\bcoleccion\b', 'colección'),
    @('\bColecciones\b', 'Colecciones'),
    @('\bcolecciones\b', 'colecciones'),
    @('\bMetodo\b', 'Método'),
    @('\bmetodo\b', 'método'),
    @('\bLudico\b', 'Lúdico'),
    @('\bludico\b', 'lúdico'),
    @('\bBasico\b', 'Básico'),
    @('\bbasico\b', 'básico'),
    @('\bDiagnostico\b', 'Diagnóstico'),
    @('\bdiagnostico\b', 'diagnóstico'),
    @('\bTambien\b', 'También'),
    @('\btambien\b', 'también'),
    @('\bAqui\b', 'Aquí'),
    @('\baqui\b', 'aquí'),
    @('\bPodras\b', 'Podrás'),
    @('\bpodras\b', 'podrás'),
    @('\bUnico\b', 'Único'),
    @('\bunico\b', 'único'),
    @('\bUnica\b', 'Única'),
    @('\bunica\b', 'única'),
    @('\bMas\b', 'Más'),
    @('\bmas\b', 'más'),
    @('\bJapones\b', 'Japonés'),
    @('\bjapones\b', 'japonés'),
    @('\bClasica\b', 'Clásica'),
    @('\bclasica\b', 'clásica'),
    @('\bPanaderia\b', 'Panadería'),
    @('\bpanaderia\b', 'panadería'),
    @('\bOptimizacion\b', 'Optimización'),
    @('\boptimizacion\b', 'optimización'),
    @('\bEstandares\b', 'Estándares'),
    @('\bestandares\b', 'estándares'),
    @('\bExito\b', 'Éxito'),
    @('\bexito\b', 'éxito'),
    @('\bAtencion\b', 'Atención'),
    @('\batencion\b', 'atención'),
    @('\bSolucion\b', 'Solución'),
    @('\bsolucion\b', 'solución'),
    @('\bInversion\b', 'Inversión'),
    @('\binversion\b', 'inversión'),
    @('\bVision\b', 'Visión'),
    @('\bvision\b', 'visión'),
    @('\bEstetica\b', 'Estética'),
    @('\bestetica\b', 'estética'),
    @('\bConstruccion\b', 'Construcción'),
    @('\bconstruccion\b', 'construcción'),
    @('\bRapido\b', 'Rápido'),
    @('\brapido\b', 'rápido'),
    @('\bFacil\b', 'Fácil'),
    @('\bfacil\b', 'fácil'),
    @('\bProximo\b', 'Próximo'),
    @('\bproximo\b', 'próximo'),
    @('\bCafe\b', 'Café'),
    @('\bcafe\b', 'café'),
    @('\bBarberia\b', 'Barbería'),
    @('\bbarberia\b', 'barbería'),
    @('\bFisico\b', 'Físico'),
    @('\bfisico\b', 'físico'),
    @('\bFisicos\b', 'Físicos'),
    @('\bfisicos\b', 'físicos'),
    @('\bPractico\b', 'Práctico'),
    @('\bpractico\b', 'práctico'),
    @('\bTactico\b', 'Táctico'),
    @('\btactico\b', 'táctico'),
    @('\bTecnico\b', 'Técnico'),
    @('\btecnico\b', 'técnico'),
    @('\bEspecifico\b', 'Específico'),
    @('\bespecifico\b', 'específico'),
    @('\bEspecificos\b', 'Específicos'),
    @('\bespecificos\b', 'específicos'),
    @('\bBasica\b', 'Básica'),
    @('\bbasica\b', 'básica'),
    @('\bBasicas\b', 'Básicas'),
    @('\bbasicas\b', 'básicas'),
    @('\bPractica\b', 'Práctica'),
    @('\bpractica\b', 'práctica'),
    @('\bTactica\b', 'Táctica'),
    @('\btactica\b', 'táctica'),
    @('\bTecnica\b', 'Técnica'),
    @('\btecnica\b', 'técnica'),
    @('\bEspecifica\b', 'Específica'),
    @('\bespecifica\b', 'específica'),
    @('\bEspecificas\b', 'Específicas'),
    @('\bespecificas\b', 'específicas'),
    @('\bComun\b', 'Común'),
    @('\bcomun\b', 'común'),
    @('\bDesafio\b', 'Desafío'),
    @('\bdesafio\b', 'desafío'),
    @('\bDesafios\b', 'Desafíos'),
    @('\bdesafios\b', 'desafíos'),
    @('\bGarantia\b', 'Garantía'),
    @('\bgarantia\b', 'garantía'),
    @('\bCategoria\b', 'Categoría'),
    @('\bcategoria\b', 'categoría'),
    @('\bCategorias\b', 'Categorías'),
    @('\bcategorias\b', 'categorías'),
    @('\bDia\b', 'Día'),
    @('\bdia\b', 'día'),
    @('\bDias\b', 'Días'),
    @('\bdias\b', 'días'),
    @('\bDinamico\b', 'Dinámico'),
    @('\bdinamico\b', 'dinámico'),
    @('\bArmonico\b', 'Armónico'),
    @('\barmonico\b', 'armónico'),
    @('\bAutentico\b', 'Auténtico'),
    @('\bautentico\b', 'auténtico'),
    @('\bEstandar\b', 'Estándar'),
    @('\bestandar\b', 'estándar'),
    @('\bHabitacion\b', 'Habitación'),
    @('\bhabitacion\b', 'habitación'),
    @('\bOrganizacion\b', 'Organización'),
    @('\borganizacion\b', 'organización'),
    @('\bEjecucion\b', 'Ejecución'),
    @('\bejecucion\b', 'ejecución'),
    @('\bProyeccion\b', 'Proyección'),
    @('\bproyeccion\b', 'proyección'),
    @('\bInnovacion\b', 'Innovación'),
    @('\binnovacion\b', 'innovación'),
    @('\bInspiracion\b', 'Inspiración'),
    @('\binspiracion\b', 'inspiración'),
    @('\bEvaluacion\b', 'Evaluación'),
    @('\bevaluacion\b', 'evaluación'),
    @('\bCotizacion\b', 'Cotización'),
    @('\bcotizacion\b', 'cotización'),
    @('Estudio', 'Estudio'),
    @('estuduio', 'estudio')
)

foreach ($pair in $corrections) {
    $content = $content -creplace $pair[0], $pair[1]
}

Set-Content -Path 'index.html' -Value $content -Encoding UTF8
Write-Host "Replaced NODO with MAROZ and fixed spelling in index.html"
